manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rschenk
      url-base: https://github.com/rschenk
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: ada1542940c3a01c0866c9fe9c30f489bc087328
      import: app/west.yml
    - name: zmk-component-raytac-dongle
      remote: rschenk
      revision: main # <-- This module pinned to the same version as ZMK
  self:
    path: config
